const jobs = [
    {
        job_no: 1,
        job_name: "Senior Odoo Developer",
        job_fun: "IT Hardware, Software",
        com_name: "Mottama Holdings Limited",
        location: "Yangon",
        salary: 1100000,
        up_time: 5,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Provide Meal & Transportation",
        hight: "An awesome company, Join a winning team, You can make a differenc",
        career: "Opportunities for promotion, Possibility for job training, Learn new skills and techniques",

        l1: "Education: Bachelor degree in Computer Science, Information Technology, or a related field.",
        l2: "Experience: Minimum 3 years of experience working with Odoo development.",
        l3: "Expert in Python, JavaScript, HTML, and XML.",
        l4: " In-depth knowledge of PostgreSQL database.",
        l5: "Extensive experience with Odoo APIs and integration with third-party systems.",

        l6: "Development and Customization: Design, develop, and customize Odoo modules as per business requirements.",
        l7: "Integration: Integrate Odoo with other third-party systems and applications.",
        l8: "Technical Support: Provide technical support and troubleshooting for Odoo-related issues.",
    },
    {
        job_no: 2,
        job_name: "System Administrator",
        job_fun: "IT Hardware, Software",
        com_name: "Myanmar Technology Gateway Co.,Ltd",
        salary: 800000,
        up_time: 1,
        up_time: "8 days ago",

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Bonus Meal Overtime Allowance Travel Allowance Ferry",
        hight: "International Standard",
        career: "Training Provide, Join with experience Team",

        l1: "Age between 25 to 35 preferred.",
        l2: "Minimum 2+ years of experience in software development/ERP.",
        l3: "Good knowledge about writing database queries, database Procedures.",
        l4: "Strong analytical and problem-solving skills, with the ability to analyze data, identify issues, and implement effective solutions.",
        l5: "Highly proficient Microsoft Office tools user especially in Excel, Word and Power point.",

        l6: "Responsible for Software Development/System analysis, designing and developing with PostgreSQL database.",
        l7: "Update, enhance, Troubleshoot and maintain databases including regularly checking for errors.",
        l8: "Create Power BI dashboards report, provide analysis of trends, forecasts and recommend actions."
    },
    {
        job_no: 3,
        job_name: "Senior Odoo Developer",
        job_fun: "IT Hardware, Software",
        com_name: "Mottama Holdings Limited",
        location: "Naypyidaw",
        salary: 900000,
        up_time: 2,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Provide Meal & Transportation",
        hight: "An awesome company, Join a winning team, You can make a differenc",
        career: "Opportunities for promotion, Possibility for job training, Learn new skills and techniques",

        l1: "Education: Bachelor degree in Computer Science, Information Technology, or a related field.",
        l2: "Experience: Minimum 3 years of experience working with Odoo development.",
        l3: "Expert in Python, JavaScript, HTML, and XML.",
        l4: " In-depth knowledge of PostgreSQL database.",
        l5: "Extensive experience with Odoo APIs and integration with third-party systems.",

        l6: "Development and Customization: Design, develop, and customize Odoo modules as per business requirements.",
        l7: "Integration: Integrate Odoo with other third-party systems and applications.",
        l8: "Technical Support: Provide technical support and troubleshooting for Odoo-related issues.",
    },
    {
        job_no: 4,
        job_name: "Database Administrator",
        job_fun: "IT Hardware, Software",
        com_name: "PRO 1 GLOBAL COMPANY LIMITED",
        location: "Yangon",
        salary: 700000,
        up_time: 3,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Bonus Meal Overtime Allowance Travel Allowance Ferry",
        hight: "International Standard",
        career: "Training Provide, Join with experience Team",

        l1: "Age between 25 to 35 preferred.",
        l2: "Minimum 2+ years of experience in software development/ERP.",
        l3: "Good knowledge about writing database queries, database Procedures.",
        l4: "Strong analytical and problem-solving skills, with the ability to analyze data, identify issues, and implement effective solutions.",
        l5: "Highly proficient Microsoft Office tools user especially in Excel, Word and Power point.",

        l6: "Responsible for Software Development/System analysis, designing and developing with PostgreSQL database.",
        l7: "Update, enhance, Troubleshoot and maintain databases including regularly checking for errors.",
        l8: "Create Power BI dashboards report, provide analysis of trends, forecasts and recommend actions."
    },
    {
        job_no: 5,
        job_name: "Technical Support - NPT",
        job_fun: "IT Hardware, Software",
        com_name: "KBZ Bank",
        location: "NayPyiTaw",
        salary: 6600000,
        up_time: 4,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Uniform Bonus Ferry Provide Sat & Sun Off",
        hight: "International Standard Fun Working Environment",
        career: "Learn new skills on the Job.",

        l1: "Possess at least a Bachelor- Degree, in IT or related fields.",
        l2: "Strong knowledge in Microsoft Office, Network Engineering (NE) and PC hardware/components maintenance.",
        l3: "Prefer to have contact centre related applications experience.",
        l4: "Problem-solving the ability to handle complex enquiries, tech related support and also day-to-day challenges involved.",
        l5: "Ability to command both spoken and written in Myanmar and English.",

        l6: "Highlight critical issues to the reporting manager and other related teams whenever necessary.",
        l7: "Solution administration, installation, troubleshooting PC / Network problem, upgrading and repairing equipment as required.",
        l8: "Keep updated of any Technical announcements related to the team and share the same for action whenever required."
    },
    {
        job_no: 6,
        job_name: "IT Support",
        job_fun: "IT Hardware, Software",
        com_name: "Golden Myanmar Alliance",
        location: "Yangon",
        salary: 500000,
        up_time: 5,

        exp: "Experienced Non-Manager",
        level: "Diploma",
        type:"Full Time",
        benefils: "Meal/ Travel Allowance",
        hight: "Fun working environment",
        career: "Learn news skills on the job",

        l1: "B.C Tech or any graduated.",
        l2: "Must have above 1-year related experiences.",
        l3: "Should be able to communicate across different levels of the organization.",
        l4: "Wi-Fi, CCTV and Software Server Maintenance",
        l5: "Ability to command both spoken and written in Myanmar and English.",

        l6: "Computer/ Printer Hardware and Software services.",
        l7: "Network devices setup, installation configuration and maintenance.",
        l8: "Knowledge of basic networking concepts including wireless and LAN."
    },
    {
        job_no: 7,
        job_name: "Flutter Developer",
        job_fun: "IT Hardware, Software",
        com_name: "Myanmar Information Technology Pte. Ltd. (MIT)",
        location: "Yangon",
        salary: 750000,
        up_time: 7,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Ferry Provided * Rewards for over performance",
        hight: "Fun working environment * International standards * Make a difference",
        career: " Opportunities for promotion * Possibility for job training",

        l1: "Bachelor Degree in Computer Science or higher",
        l2: "Minimum 1 or 2 Years relevant experiences in software development",
        l3: "Knowledge of system frameworks including  Git and GitHub.",
        l4: "Good communication skills",
        l5: "Experience in developing and implementations Enterprise and Business applications",

        l6: "Develop mobile applications using Flutter framework",
        l7: "Collaborate with cross-functional teams to define, design, and ship new features",
        l8: "Write clean, maintainable, and efficient code"
    },
    {
        job_no: 8,
        job_name: "IT Engineer (Thilawa SEZ)",
        job_fun: "IT Hardware, Software",
        com_name: "TOA Coating (Myanmar) Co., Ltd",
        location: "Mandalay",
        salary: 500000,
        up_time: 5,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Rewards over performance",
        hight: "International Standard",
        career: "Possibility for job training",

        l1: "Education: Bachelor degree in computer science / technology",
        l2: "Experience: Minimum 3 year of experience in professional IT role  ",
        l3: "Strong communication skills and a proactive attitude towards problem-solving",
        l4: "Ability to work independently and under pressure to meet internal customer needs.      ",
        l5: "Ability to write and communicate in English  ",

        l6: "Install and configure computer hardware, software systems, networks, printers, scanners, and other IT equipment.",
        l7: "Respond promptly to service issues and requests from users.",
        l8: "Register all IT fixed assets and maintain monthly reports."
    },
    {
        job_no: 9,
        job_name: "Senior Software Developer",
        job_fun: "IT Hardware, Software",
        com_name: "Myanmar Metro Bank",
        location: "Naypyidaw",
        salary: 1100000,
        up_time: 5,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Rewards over performance",
        hight: "Join an experienced team",
        career: "Learn new skills on the job - Management potential",

        l1: "Bachelor's or Master's degree in Computer Science or a related discipline.",
        l2: "Minimum of 5 years of experience in software development, with a preference for those versed in banking or financial sectors.",
        l3: "Demonstrable expertise in major programming languages including but not limited to Java, C++, or Python.",
        l4: "Independent work ethic, adept at juggling priorities in a dynamic setting.",
        l5: "Flexibility to operate beyond standard business hours when necessary.",

        l6: "Design and maintain the core banking platform to be in line with the business strategies.",
        l7: "Assure steadfast compliance with core banking protocols, incorporating regulatory directives.",
        l8: "Delve deep into core banking systems features, like deposits, loans, and payment processing, ensuring our platform mirrors industry benchmarks."
    },
    {
        job_no: 10,
        job_name: "Assistant Product Manager",
        job_fun: "IT Hardware, Software",
        com_name: "KBZ Bank",
        location: "Yangon",
        salary: 1200000,
        up_time: 7,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Bonus",
        hight: "International Standards",
        career: "Management Potential",

        l1: "Equivalent to graduation from an accredited college or university with a degree in computer science, information systems, information technology, public policy, business, or closely related field,",
        l2: "Three (3) years of experience working as a product manager for a digital product that is in use by people today.",
        l3: "One (1) year of experience serving as a lead or in a supervisory or management capacity is desirable.",
        l4: "A Master Degree is preferred.",
        l5: "Self-motivated and Organized",

        l6: "Managing the Mini App Product planning and its lifecycle",
        l7: "Clear understanding of user-centred and iterative design, and the agile development process for Financial systems",
        l8: "Experience re-designing complex products, services, or transactions to be more simple, beautiful, and easy to use."
    },
    {
        job_no: 11,
        job_name: "Junior Web Developer",
        job_fun: "IT Hardware, Software",
        com_name: "PRO 1 GLOBAL COMPANY LIMITED",
        location: "Yangon",
        salary: 1100000,
        up_time: 2,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Bonus Meal Overtime Allowance Travel Allowance",
        hight: "International Standard",
        career: "Training Provide Join with experience Team",

        l1: "Any Graduated",
        l2: "Age between 25 to 35 preferred",
        l3: "At least 1 year Web Developer or a similar role (preferable)",
        l4: "Computer literacy and proficient in MS Office",
        l5: "Advanced English communication skills (written and verbal)",

        l6: "Good knowledge of HTML5, CSS (tailwind, bootstrap), JavaScript, PHP, Laravel",
        l7: "Understanding of OOP concept, Design Pattern and Anti Patterns",
        l8: "Proficient understanding of code versioning tools (Git)"
    },
    {
        job_no: 12,
        job_name: "Android Developer",
        job_fun: "IT Hardware, Software",
        com_name: "Linn IT Solution Co.,Ltd",
        location: "NayPyiTaw",
        salary: 1200000,
        up_time: 9,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Employee meals * Based on performance salary * Annual Bonus",
        hight: "Experienced Team * Cutting-Edge Technologies * Quality Assurance",
        career: " Promotion Opportunities * Collaborative Environment ",

        l1: "At least Degree Holder, preferably Computer Science related Degree",
        l2: "More than 3years experience in Android application design and development",
        l3: "At least 2 Android applications design and development that involve integration with backend web service or API call",
        l4: "Experience in releasing Android application to Google Play Store",
        l5: "Strong in Android SDK and components, Android design principles",

        l6: "Prototype, design, build and maintain Android application for mobile devices and tablet and TV app",
        l7: " Integrate with backend system by collaborating closely with backend development team",
        l8: "Design and execute software quality assurance test plan for Android application"
    },
    {
        job_no: 13,
        job_name: "Web Developer (PHP, Laravel)",
        job_fun: "IT Hardware, Software",
        com_name: "Linn IT Solution Co.,Ltd",
        location: "NayPyiTaw",
        salary: 900000,
        up_time: 1,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Employee meals * Based on performance salary * Annual Bonus",
        hight: "Experienced Team * Cutting-Edge Technologies * Quality Assurance",
        career: "Promotion Opportunities * Collaborative Environment",

        l1: "PHP and Laravel Framework skill is a must",
        l2: "HTML, CSS, Java Script skill is a must",
        l3: "Familiar with React JS is a bonus",
        l4: "Positive working attitude is a must",
        l5: "Minimum 2 years experience as a web developer",

        l6: "Writing well designed, testable, efficient code by using best software development practices.",
        l7: "Editing, writing, or designing Website content, and directing team members who produce content.",
        l8: "Creating website layout/user interfaces by using standard HTML/CSS practices."
    },
    {
        job_no: 14,
        job_name: "Requirement Analyst - UAT",
        job_fun: "IT Hardware, Software",
        com_name: "KBZ Bank",
        location: "Yangon",
        salary: 1100000,
        up_time: 10,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Bonus",
        hight: ":International Standards",
        career: "Possibility for job training",

        l1: "Bachelor Degree from a recognized college or university preferably in Computer Science and Information Technology",
        l2: "More than 3 years experience in a Requirement Analyst especially in mobile application",
        l3: "Hands-on knowledge of Software Development Life Cycle principles and Quality",
        l4: "Experience in the design drawing sequence diagram, flow chart, swim lane.",
        l5: "Preferably have knowledge on banking and financial service",

        l6: "Work closely with the allocated stakeholders to turn their requirements into a viable product by defining the true problem, scoping the business case and discovering the business process and related changes.",
        l7: "To engage with key stakeholder acquiring/Analysing the required information to complete the Business Required Documents.",
        l8: " Knowledge in Project Management/Methodologies"
    },
    {
        job_no: 15,
        job_name: "IT Business Analyst",
        job_fun: "IT Hardware, Software",
        com_name: "GRAND GUARDIAN NIPPON LIFE INSURANCE",
        location: "Yangon",
        salary: 800000,
        up_time: 15,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Bonus - Overtime Payment",
        hight: "Fun Working Environment - International Standards",
        career: "Training & Development Program",

        l1: "Bachelor degree in Information Technology, Computer Science, or a related field.",
        l2: "Minimum of 7-9 years of experience in application management, IT project management, or business analysis or a related field",
        l3: "Strong understanding of software development lifecycle (SDLC) and project management methodologies.",
        l4: "Knowledge of database management, SQL, and data integration techniques.",
        l5: "Strong problem-solving and analytical skills.",

        l6: " Knowledge of database management, SQL, and data integration techniques",
        l7: "Excellent technical documentation skills including generation of process documentation and reports.",
        l8: "Maintain accurate and up-to-date documentation for all IT processes and systems."
    },
    {
        job_no: 16,
        job_name: "Software Development Engineer",
        job_fun: "IT Hardware, Software",
        com_name: "Ooredoo Myanmar",
        location: "Yangon",
        salary: 1100000,
        up_time: 2,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Ooredoo Myanmar Family Mobile Plan",
        hight: "An Awesome Company with 5 star office facilities",
        career: "Ongoing Training and Development Learning new skills",

        l1: "A bachelor degree in computer science. ",
        l2: "At least 5+ years of experience in software development/ software engineering.",
        l3: "Minimum 3 to 4 years of hands-on experience specifically in Laravel and React.js / Vue.js development.",
        l4: "Good experience in version control systems, particularly Git, for code collaboration and management.",
        l5: "Strong understanding of front-end technologies such as HTML5, CSS3, and JavaScript",

        l6: "Collaborate with UX/UI designers to translate design mockups into responsive and intuitive user interfaces.",
        l7: "Performing validation and verification testing.",
        l8: "Responsible for updating and maintaining the software and products."
    },
    {
        job_no: 17,
        job_name: "IT Support Specialist",
        job_fun: "IT Hardware, Software",
        com_name: "Frontend Developer",
        location: "Mandalay",
        salary: 700000,
        up_time: 5,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Annual performance and salary review,",
        hight: "Fun Working Environment",
        career: "Promotion Opportunities",

        l1: "Proven experience as a Front End Developer or similar role.",
        l2: "Strong proficiency in front end technologies such as HTML5, CSS3, JavaScript (ES6+), Bootstrap, Tailwind",
        l3: "Experience with React, Webpack, SCSS, and Pug is a plus.",
        l4: "Solid understanding of responsive web design principles.",
        l5: "Experience with version control systems such as Git .",

        l6: "Develop user-facing features and components using front end technologies such as HTML5, CSS3, JavaScript (ES6+)",
        l7: "Collaborate with UI/UX designers to translate design wireframes into responsive and visually appealing web pages.",
        l8: "Stay up-to-date with the latest front end development trends, tools, and technologies"
    },
    {
        job_no: 18,
        job_name: "NOC Engineer",
        job_fun: "IT Hardware, Software",
        com_name: "KBZ Bank",
        location: "Naypyidaw",
        salary: 800000,
        up_time: 25,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Bonus + Ferry",
        hight: "International Standards Leading Bank in Myanmar",
        career: "Opportunities for promotion Possibility",

        l1: "Bachelor degree or Diploma in Creative Design or related fields",
        l2: "Minimum 2 years of experience with UI/UX design",
        l3: "Minimum 1 year of user experience research",
        l4: "Highly-motivated self-starter with a passion for making high quality software",
        l5: "Strong communication skills, strong sense of ownership and drive",

        l6: "Design and deliver wireframes, user stories, user journeys, and Hi-fi mockups optimized for a wide range of devices and interfaces.",
        l7: "Identify design problems and find creative ways to solve UX problems (e.g. usability, findability)",
        l8: "Communicate design ideas and prototypes to developers and business owners."
    },
    {
        job_no: 19,
        job_name: "Team Lead Full Stack Software Engineer",
        job_fun: "IT Hardware, Software",
        com_name: "KBZ Bank",
        location: "Yangon",
        salary: 1100000,
        up_time: 15,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Quarterly Bonus Ferry (YGN area) Uniform Health Care Support",
        hight: "International Standards Leading Bank in Myanmar",
        career: "Opportunities for promotion Possibility",

        l1: "Bachelor degree in Computer Science or related fields",
        l2: "2+ years working experience and In-depth knowledge of relational databases (e.g. MSSQL, Oracle, Postgre, MySQL)",
        l3: "5+ years of professional experience in C# (or other object-oriented programming languages) and/or professional experience in web technologies such as HTML5, CSS, JavaScript, Json",
        l4: "jQuery and applicable frameworks like MVC",
        l5: "A high level of modern software engineering experience (e.g.MicroService, FaaS, Containerization, CI/CD, High Availability..etc)",

        l6: "Develop and deliver high quality code which is well tested, well documented and consistently bugs free",
        l7: "Design and build database schemas with integrity and scalability with data access layers that are optimized for performance and security",
        l8: "Analyse codes in purpose of optimization and troubleshooting with rapid manner"
    },
    {
        job_no: 20,
        job_name: "Senior Java Developer",
        job_fun: "IT Hardware, Software",
        com_name: "Wave Money",
        location: "Mawlamyine",
        salary: 950000,
        up_time: 5,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "BENEFITS - Medical, Life Insurance - Mobile Usage allowance - Ferry",
        hight: "Myanmar's First Mobile Financial Services Provider",
        career: "Growing organization - Develop your career",

        l1: "Diploma, Bachelor Degree or Master in Computer Science or Technology",
        l2: "5+ years of experience in API/backend/middleware development with API gateways and API Manager",
        l3: "Expertise in one or more of the following: Java, J2EE, Spring Framework, Micro Services and Frameworks",
        l4: "Excellent understanding of programming/design patterns, algorithms, and ability to build elegant solutions with simpler and fewer line of code to complex problems",
        l5: "Excellent communication and interpersonal skills.  Articulates thoughts and ideas clearly, concisely, and persuasively",

        l6: "Delivery of products, features and configuration changes which enables the product pipeline",
        l7: "Support & participate in platform server outage/any other middleware incident/issue",
        l8: "Positive engagement with technology and non-technology stakeholders which drives outcomes."
    },
    {
        job_no: 21,
        job_name: "Senior Quantity Surveyor",
        job_fun: "Architecture, Design",
        com_name: "Comet Design and Decoration",
        location: "Yangon",
        salary: 1100000,
        up_time: 15,

        exp: "Experienced Non-Manager",
        level: "Diploma",
        type:"Full Time",
        benefils: "Uniform",
        hight: "Fun Working Environment",
        career: "Promotion Opportunities",

        l1: "Bachelor degree or diploma holder in the respective field",
        l2: "At least 5 years of experience as a quantity surveyor",
        l3: "Strong analytical and critical thinking skills",
        l4: "Good interpersonal skills",
        l5: "Ability to organise team members and engineers",

        l6: "Prepare detailed cost estimates for construction, interior decoration and furniture projects.",
        l7: "Develop and manage project budgets, ensuring financial feasibility and profitability.",
        l8: "Monitor project progress and ensure adherence to the budget and timeline."
    },
    {
        job_no: 22,
        job_name: "3D Visualizer/Designer",
        job_fun: "Architecture, Design",
        com_name: "MARGA GROUP",
        location: "Yangon",
        salary: 800000,
        up_time: 5,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Rewards over performance",
        hight: "Join an experienced team",
        career: "Learn new skills on the job",

        l1: "Minimum 3 to 5 years working experience within achitectural firms of more than 5 years of freelance working experience",
        l2: "Bachelor degree/ diploma in architecture or relevant design field",
        l3: "Strong communication skills with teams and ability to work independently",
        l4: "Basic English Skills to communicate with senior management (Written/Verbal)",
        l5: "Proficiency in producing presentations and 3D interior and exterior realistic renderings using :3D Max, AutoCAD, SketchUp, ArcfhiCAD/Revit, Adobe Photoshop, MS Office (Powerpoint), Enscape (Preferred but not required)",

        l6: "Working closely with architectural design team and site team to plan and visualize all design & constructiion projects",
        l7: "Preparing high quality 3D models, renderings/animations and material presnetations for senior management.",
        l8: "Ensuring design drawings to be interpreted as 3D renderings accurately and visually stunning"
    },
    {
        job_no: 23,
        job_name: "2D Jewellery Designer",
        job_fun: "Architecture, Design",
        com_name: "My Jewels",
        location: "Naypyidaw",
        salary: 1100000,
        up_time: 4,

        exp: "Experienced Non-Manager",
        level: "Diploma",
        type:"Full Time",
        benefils: "Uniform - Transportation Allowance - Birthday Entertainment",
        hight: "Fun Working Environment - Creative Workplace",
        career: "Opportunities for promotion",

        l1: "Must be a graduate of art school or have no school issues.",
        l2: "Must be 25 to 35 years old.",
        l3: "Must be honest and willing to work hard.",
        l4: "Must have at least 3-5 years of relevant work experience.",
        l5: "University of Culture graduate will be preferred.",

        l6: "Must be able to draw 2D jewelry designs with interest.",
        l7: "Must be able to follow the current trend.",
        l8: "He must be able to create and design his own jewelry designs."
    },
    {
        job_no: 24,
        job_name: "Senior Interior Designer",
        job_fun: "Architecture, Design",
        com_name: "Comet Design and Decoration",
        location: "Yangon",
        salary: 700000,
        up_time: 35,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Rewards over performance",
        hight: "Join an experienced team",
        career: "Learn new skills on the job",

        l1: "Must be a Bachelor of Architecture or Diploma in Interior Design.",
        l2: "Must have at least (3) years of work experience.",
        l3: "Must have experience in Interior Designer & Built in Furniture Design Details.",
        l4: "Must be able to draw Auto Cad, Sketch Up, 3DMax, 3D modeling & Rendering.",
        l5: "Must have his own creative design idea who understands the design concept, installation, and materials.",

        l6: "Attend the meeting and collect information of clients",
        l7: "3D Conceptual Design and Visualizations   ",
        l8: "Planning the space for Layout Plan  "
    },
    {
        job_no: 25,
        job_name: "Senior Site Engineer",
        job_fun: "Architecture, Design",
        com_name: "Comet Design and Decoration",
        location: "NayPyiTaw",
        salary: 900000,
        up_time: 15,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Rewards over performance",
        hight: "Join an experienced team",
        career: "Learn new skills on the job",

        l1: "B.E (Civil)/ B.Tech(Civil)/ A.G.T.I (Civil)",
        l2: "Minimum 5 years of relevant experience in managing of construction project and interior design project",
        l3: "Strong analytical skill",
        l4: "Sound communication and interpersonal skills",
        l5: "Computer proficiency in MS project,Excel and Work",

        l6: "Review and analyze the site drawing (site plan, elevations and dimensions etc.)",
        l7: "Assiging and instruct tasks to labour properly on the site.",
        l8: "Monitoring the ongoing works to ensure and align with the drawing and specifications."
    },
    {
        job_no: 26,
        job_name: "Senior Graphic Designer",
        job_fun: "Architecture, Design",
        com_name: "Excellent Fortune Development Group",
        location: "Yangon",
        salary: 700000,
        up_time: 8,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Ferry Provide * Lunch Provide * Sat & Sun (Off) * Group Life Insurance",
        hight: "Join an experience Team",
        career: "Possibility for job training",

        l1: "Minimum of (3) years of professional graphic design experience, with a strong portfolio showcasing a range of design projects.",
        l2: "Proficiency in design software such as Adobe Creative Suite (Photoshop, Illustrator, InDesign).",
        l3: "Excellent communication and presentation skills, with the ability to articulate design concepts and decisions to stakeholders.",
        l4: "Proven experience in leading design projects and mentoring junior designers.",
        l5: "Ability to work independently and as part of a team in a fast-paced environment.",

        l6: "Lead and execute the design process for various projects, including digital, print, and multimedia",
        l7: "Develop and maintain brand guidelines to ensure consistency across all marketing materials.",
        l8: "Create visually appealing graphics, illustrations, and layouts for marketing campaigns, websites, social media, and other platforms."
    },
    {
        job_no: 27,
        job_name: "Jr.Architect",
        job_fun: "Architecture, Design",
        com_name: "Bhone Shwe Pyi Company Limited",
        location: "Yangon",
        salary: 900000,
        up_time: 5,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Rewards for overperformance",
        hight: "You can make a difference",
        career: "Learn New Skills on the Job Promotion Opportunities",

        l1: "Either Bachelor or a Diploma in Architecture, Interior Designs or equivalent. ",
        l2: "Preferred 1 year of Junior Architect experience.",
        l3: "Limited Fluency and Understanding of English.",
        l4: "Autocad 2D,3D & Sketchup",
        l5: "At least 1 year experience in Junior Archiect",

        l6: "Responsible for assisting design development across different stages.",
        l7: "Attends Project Meeting and visit sites with Architects",
        l8: "Development of Detailed Drawings and Concept Drawings."
    },
    {
        job_no: 28,
        job_name: "Architect",
        job_fun: "Architecture, Design",
        com_name: "Bhone Shwe Pyi Company Limited",
        location: "Yangon",
        salary: 700000,
        up_time: 25,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Rewards over Performance Occasional Company Lunches",
        hight: "Make a difference Join an experienced team",
        career: "Promotion Opportunities Management Potential",

        l1: "Bachelor's Degree or Diploma in Architecture or related field",
        l2: "Proficiency in SketchUp, AutoCAD, Lumion and limited knowledge of Revit.",
        l3: "High experience in development of Hospitality Interior Designs.",
        l4: "Limited knowledge of Building facade and Factory Design Concepts.",
        l5: "Experience with project management and budgeting",

        l6: "Responsible for running Designs from Conceptual Designs, Space Planning, Renderings to Detailed Drawings.",
        l7: "Proficiency in production of exceptional interior works.",
        l8: "Good knowledge of various architecture design approaches."
    },
    {
        job_no: 29,
        job_name: "Project Coordinator (Interior Design)",
        job_fun: "Architecture, Design",
        om_name: "Mahaland",
        location: "Naypyidaw",
        salary: 600000,
        up_time: 9,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Meal Allowance Transportation Allowance Life Insurance",
        hight: "You can make a difference",
        career: "Opportunities for promotion",

        l1: "B.Arch / Dip in Interior Design Diploma from an accredited college",
        l2: "Relevant and appropriate experience in project coordinator roles within reputable design firms",
        l3: "Substantial experience with workplace interiors",
        l4: "Teamwork, coordination, mentoring, and motivation",
        l5: "Experience with Photoshop, AutoCAD, Sketch-UP and Microsoft Office",

        l6: "Carry out work plans for each project, managing creative and technical design delivery.  ",
        l7: "Day-to-day responsibility for developing design concepts based on the programming requirements and budget parameters and coordinating project documentation.  ",
        l8: "Coordinates the team activities in preparing construction and furniture drawings and specifications.  "
    },
    {
        job_no: 30,
        job_name: "UIUX Designer",
        job_fun: "IT Hardware, Software",
        com_name: "KBZ Bank",
        location: "Naypyidaw",
        salary: 900000,
        up_time: 15,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Quarterly Bonus Ferry (YGN area) Uniform Health Care Support",
        hight: "International Standards Leading Bank in Myanmar",
        career: "Opportunities for promotion Possibility",

        l1: "Bachelor degree or Diploma in Creative Design or related fields",
        l2: "Minimum 2 years of experience with UI/UX design",
        l3: "Minimum 1 year of user experience research",
        l4: "Highly-motivated self-starter with a passion for making high quality software",
        l5: "Strong communication skills, strong sense of ownership and drive",

        l6: "Design and deliver wireframes, user stories, user journeys, and Hi-fi mockups optimized for a wide range of devices and interfaces.",
        l7: "Identify design problems and find creative ways to solve UX problems (e.g. usability, findability)",
        l8: "Communicate design ideas and prototypes to developers and business owners."
    },
    {
        job_no: 31,
        job_name: "Graphic Designer",
        job_fun: "Architecture, Design",
        com_name: "PRO 1 GLOBAL COMPANY LIMITED",
        location: "Yangon",
        salary: 990000,
        up_time: 22,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type:"Full Time",
        benefils: "Ferry Provide * Lunch Provide * Sat & Sun (Off) * Group Life Insurance",
        hight: "Join an experience Team",
        career: "Possibility for job training",

        l1: "Age between 25 to 35 preferred.",
        l2: "Minimum 2+ years of experience in software development/ERP.",
        l3: "Good knowledge about writing database queries, database Procedures.",
        l4: "Strong analytical and problem-solving skills, with the ability to analyze data, identify issues, and implement effective solutions.",
        l5: "Highly proficient Microsoft Office tools user especially in Excel, Word and Power point.",

        l6: "Responsible for Software Development/System analysis, designing and developing with PostgreSQL database.",
        l7: "Update, enhance, Troubleshoot and maintain databases including regularly checking for errors.",
        l8: "Create Power BI dashboards report, provide analysis of trends, forecasts and recommend actions."
    },
    {
        job_no: 32,
        job_name: "Underwriting Officer",
        job_fun: "Customer Service, Support",
        com_name: "KBZ Bank",
        location: "Yangon",
        salary: 990000,
        up_time: 22,

        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Bonus Sat, Sun and public Holidays Off",
        highlight: "Make a difference",
        career: "Learn new skills on job",

        l1: "Degree Holder or higher in Business Admin or any other discipline",
        l2: "Credit underwriting experience for minimum 3 year",
        l3: "Exceptional communication in English/Burmese and interpersonal skills.",
        l4: "Strong leadership and people management skills.",
        l5: "Excellent problem-solving and analytical abilities.",

        l6: "Have a good understanding of lending procedures and customer service experience.",
        l7: "Approve loans within specified limits and refer loan applications outside those limits to management for approval.",
        l8: "Analyse applicants' financial status, credit, and property evaluations to determine feasibility of granting loans."
    },
    {
        job_no: 33,
        job_name: "Senior Support Consultant",
        job_fun: "Customer Service, Support",
        com_name: "Vanguard Business Solutions & Consulting",
        location: "Mandalay",
        salary: 1200000,
        up_time: 30,
        exp: "Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Annual Bonus * Flexible Working Hours",
        highlight: "Leading a Dynamic Team",
        career: "Career Advancement Opportunities",
        l1: "Bachelor's degree in computer science, information technology, or related field (or equivalent experience).",
        l2: "Requires a minimum of 5 years of experience in supporting ERP-related field",
        l3: "Strong leadership and people management skills.",
        l4: "Excellent problem-solving and analytical abilities.",
        l5: "Technical proficiency in software and technology troubleshooting.",
        l6: "Manage escalated ERP-related issues, collaborating with technical teams to ensure timely resolution and minimal disruption to business operations.",
        l7: "Analyse and troubleshoot complex system issues, identify root causes, and implement solutions.",
        l8: "Interact with software providers and vendors to coordinate technical support, troubleshoot issues, and manage software updates."
    },
    {
        job_no: 34,
        job_name: "Customer Support Specialist",
        job_fun: "Customer Service, Support",
        com_name: "Myanmar Technology Gateway Co.,Ltd",
        location: "Yangon",
        salary: 800000,
        up_time: 15,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Annual Bonus * Flexible Working Hours",
        highlight: "Customer-Centric Role",
        career: "Professional Development Programs",
        l1: "Bachelor's degree in any field.",
        l2: "Minimum 2 years of experience in customer support.",
        l3: "Strong communication and interpersonal skills.",
        l4: "Excellent problem-solving abilities.",
        l5: "Proficient in customer service software and tools.",
        l6: "Respond to customer inquiries and provide timely solutions.",
        l7: "Maintain accurate records of customer interactions.",
        l8: "Collaborate with teams to improve customer satisfaction."
    },
    {
        job_no: 35,
        job_name: "Technical Support Engineer",
        job_fun: "Customer Service, Support",
        com_name: "Myanmar Technology Gateway Co.,Ltd",
        location: "Naypyidaw",
        salary: 1100000,
        up_time: 20,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Stock Options * Flexible Working Hours",
        highlight: "Tech-Savvy Role",
        career: "Continuous Learning Opportunities",
        l1: "Bachelor's degree in Computer Science or related field.",
        l2: "Minimum 3 years of experience in technical support.",
        l3: "Proficiency in troubleshooting and resolving technical issues.",
        l4: "Strong problem-solving and analytical skills.",
        l5: "Experience with support ticketing systems.",
        l6: "Provide technical assistance to customers.",
        l7: "Diagnose and troubleshoot software and hardware issues.",
        l8: "Document technical processes and solutions."
    },
    {
        job_no: 36,
        job_name: "Customer Service Manager",
        job_fun: "Customer Service, Support",
        com_name: "Wave Money",
        location: "Yangon",
        salary: 1400000,
        up_time: 25,
        exp: "Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Performance Bonus * Company Car",
        highlight: "Leadership in Service",
        career: "Professional Development Programs",
        l1: "Bachelor's degree in Business Administration or related field.",
        l2: "Minimum 5 years of experience in customer service management.",
        l3: "Strong leadership and organizational skills.",
        l4: "Excellent problem-solving and decision-making abilities.",
        l5: "Proficiency in customer service software and tools.",
        l6: "Oversee and manage the customer service team.",
        l7: "Develop and implement customer service policies.",
        l8: "Monitor customer satisfaction and improve service quality."
    },
    {
        job_no: 37,
        job_name: "Customer Relationship Officer",
        job_fun: "Customer Service, Support",
        com_name: "Trust Bank",
        location: "Yangon",
        salary: 900000,
        up_time: 18,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Annual Bonus * Career Growth",
        highlight: "Building Customer Trust",
        career: "Training and Development Programs",
        l1: "Bachelor's degree in Business or related field.",
        l2: "Minimum 2 years of experience in customer relationship management.",
        l3: "Strong communication and interpersonal skills.",
        l4: "Excellent problem-solving and analytical abilities.",
        l5: "Proficient in CRM software.",
        l6: "Manage customer accounts and relationships.",
        l7: "Address customer inquiries and resolve issues.",
        l8: "Identify opportunities to improve customer satisfaction."
    },
    {
        job_no: 38,
        job_name: "Customer Service Executive",
        job_fun: "Customer Service, Support",
        com_name: "Myanmar Metro Bank",
        location: "Mandalay",
        salary: 850000,
        up_time: 22,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Flexible Working Hours * Performance Bonus",
        highlight: "Enhancing Customer Experience",
        career: "Career Development Opportunities",
        l1: "Bachelor's degree in any field.",
        l2: "Minimum 3 years of experience in customer service.",
        l3: "Excellent communication and problem-solving skills.",
        l4: "Strong organizational abilities.",
        l5: "Proficient in customer service software.",
        l6: "Respond to customer inquiries via phone, email, and chat.",
        l7: "Resolve customer issues and ensure satisfaction.",
        l8: "Document customer interactions and feedback."
    },
    {
        job_no: 39,
        job_name: "Technical Support Specialist",
        job_fun: "Customer Service, Support",
        com_name: "Sea Lion Co.,Ltd",
        location: "Yangon",
        salary: 1000000,
        up_time: 19,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Performance Bonus * Stock Options",
        highlight: "Tech Support Excellence",
        career: "Professional Growth Opportunities",
        l1: "Bachelor's degree in Information Technology or related field.",
        l2: "Minimum 3 years of experience in technical support.",
        l3: "Proficiency in troubleshooting technical issues.",
        l4: "Strong problem-solving and analytical skills.",
        l5: "Experience with ticketing systems.",
        l6: "Provide technical support to clients.",
        l7: "Diagnose and resolve software and hardware issues.",
        l8: "Maintain detailed documentation of technical issues."
    },
    {
        job_no: 40,
        job_name: "Business Analyst",
        job_fun: "Customer Service, Support",
        com_name: "Myanmar Information Technology Pte. Ltd. (MIT)",
        location: "Yangon",
        salary: 1150000,
        up_time: 21,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Annual Bonus * Professional Training",
        highlight: "Analyze Business Data",
        career: "Professional Growth",
        l1: "Proven experience as a business analyst.",
        l2: "Proficiency in data analysis tools and software.",
        l3: "Strong analytical and problem-solving skills.",
        l4: "Excellent communication and presentation skills.",
        l5: "Knowledge of business process modeling.",
        l6: "Analyze business needs and identify solutions.",
        l7: "Document and communicate the results of your efforts.",
        l8: "Collaborate with stakeholders to understand their requirements."
    },
    {
        job_no: 41,
        job_name: "Digital Marketing Specialist",
        job_fun: "Customer Service, Support",
        com_name: "Bhone Shwe Pyi Company Limited",
        location: "Mandalay",
        salary: 950000,
        up_time: 23,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Flexible Working Hours * Performance Bonus",
        highlight: "Innovative Marketing Strategies",
        career: "Continuous Learning Opportunities",
        l1: "Proven experience in digital marketing.",
        l2: "Excellent understanding of digital marketing concepts and best practices.",
        l3: "Experience with B2C social media, Google AdWords and email campaigns.",
        l4: "Perfect knowledge of web analytics tools (e.g. Google Analytics, NetInsight, WebTrends etc.).",
        l5: "Skills and experience in creative content writing.",
        l6: "Collaborate with designers to improve user experience.",
        l7: "Measure performance of digital marketing efforts using a variety of Web analytics tools.",
        l8: "Acquire insight in online marketing trends and keep strategies up-to-date."
    },
    {
        job_no: 42,
        job_name: "Operations Manager",
        job_fun: "Customer Service, Support",
        com_name: "Vanguard Business Solutions & Consulting",
        location: "Yangon",
        salary: 1250000,
        up_time: 32,
        exp: "Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Performance Bonus * Company Car",
        highlight: "Efficient Operations",
        career: "Leadership Training",
        l1: "Proven experience as an operations manager.",
        l2: "Excellent organizational and leadership abilities.",
        l3: "Outstanding communication and people skills.",
        l4: "Knowledge of industry’s legal rules and guidelines.",
        l5: "In depth knowledge of diverse business functions and principles (e.g. supply chain, finance, customer service etc.).",
        l6: "Oversee the daily operations of the company.",
        l7: "Develop and implement operational policies and procedures.",
        l8: "Monitor and analyze the effectiveness of business operations."
    },
    {
        job_no: 43,
        job_name: "Content Writer",
        job_fun: "Customer Service, Support",
        com_name: "BCD PUBLISHING",
        location: "Yangon",
        salary: 800000,
        up_time: 20,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Annual Bonus * Remote Work Option",
        highlight: "Creative Writing",
        career: "Career Growth Opportunities",
        l1: "Proven experience as a content writer.",
        l2: "Excellent writing and editing skills in English.",
        l3: "Strong research skills.",
        l4: "Creativity and ability to develop original content.",
        l5: "Knowledge of SEO best practices.",
        l6: "Write clear, attractive copy with a distinct voice.",
        l7: "Collaborate with designers, PR and other professionals on large- and small-scale marketing projects (e.g. email campaigns and landing pages).",
        l8: "Conduct high-quality research and interviews."
    },
    {
        job_no: 44,
        job_name: "Customer Support Agent",
        job_fun: "Customer Service, Support",
        com_name: "Help Desk Solutions",
        location: "Naypyidaw",
        salary: 750000,
        up_time: 15,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Flexible Working Hours * Annual Bonus",
        highlight: "Customer Assistance",
        career: "Professional Development",
        l1: "Experience in customer support or related field.",
        l2: "Excellent communication skills.",
        l3: "Strong problem-solving abilities.",
        l4: "Ability to manage multiple tasks and priorities.",
        l5: "Proficiency in customer support software.",
        l6: "Respond to customer inquiries via phone, email, and chat.",
        l7: "Resolve customer issues and ensure satisfaction.",
        l8: "Document customer interactions and feedback."
    },
    {
        job_no: 45,
        job_name: "Customer Success Manager",
        job_fun: "Customer Service, Support",
        com_name: "Atom",
        location: "Yangon",
        salary: 1300000,
        up_time: 25,
        exp: "Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Performance Bonus * Career Growth",
        highlight: "Customer Satisfaction",
        career: "Leadership Training",
        l1: "Experience in customer success or account management.",
        l2: "Strong communication and interpersonal skills.",
        l3: "Ability to manage and prioritize multiple accounts.",
        l4: "Proficiency in CRM software.",
        l5: "Strong problem-solving skills.",
        l6: "Build and maintain strong relationships with customers.",
        l7: "Ensure customer satisfaction and retention.",
        l8: "Collaborate with internal teams to meet customer needs."
    },
    {
        job_no: 46,
        job_name: "Service Desk Analyst",
        job_fun: "Customer Service, Support",
        com_name: "Linn IT Solution Co.,Ltd",
        location: "Mandalay",
        salary: 850000,
        up_time: 18,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Annual Bonus * Flexible Working Hours",
        highlight: "Technical Assistance",
        career: "Professional Growth Opportunities",
        l1: "Experience in IT support or related field.",
        l2: "Strong problem-solving and analytical skills.",
        l3: "Excellent communication skills.",
        l4: "Proficiency in support ticketing systems.",
        l5: "Knowledge of ITIL processes.",
        l6: "Provide technical assistance to end-users.",
        l7: "Diagnose and resolve technical issues.",
        l8: "Document support processes and solutions."
    },
    {
        job_no: 47,
        job_name: "Customer Care Executive",
        job_fun: "Customer Service, Support",
        com_name: "KBZ Bank",
        location: "Yangon",
        salary: 950000,
        up_time: 20,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Performance Bonus * Annual Bonus",
        highlight: "Customer Engagement",
        career: "Career Development Opportunities",
        l1: "Experience in customer care or related field.",
        l2: "Strong communication and interpersonal skills.",
        l3: "Excellent problem-solving abilities.",
        l4: "Ability to manage multiple tasks and priorities.",
        l5: "Proficiency in customer care software.",
        l6: "Engage with customers to understand their needs.",
        l7: "Resolve customer issues and ensure satisfaction.",
        l8: "Document customer interactions and feedback."
    },
    {
        job_no: 48,
        job_name: "Technical Support Lead",
        job_fun: "Customer Service, Support",
        com_name: "Myanmar Technology Gateway Co.,Ltd",
        location: "Naypyidaw",
        salary: 1200000,
        up_time: 22,
        exp: "Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Stock Options * Performance Bonus",
        highlight: "Leading Technical Support",
        career: "Leadership Training",
        l1: "Experience in technical support leadership.",
        l2: "Strong problem-solving and analytical skills.",
        l3: "Excellent communication skills.",
        l4: "Proficiency in support ticketing systems.",
        l5: "Knowledge of ITIL processes.",
        l6: "Lead and manage the technical support team.",
        l7: "Diagnose and resolve complex technical issues.",
        l8: "Develop and implement support processes and solutions."
    },
    {
        job_no: 49,
        job_name: "Customer Service Representative",
        job_fun: "Excellent Fortune Development Group",
        com_name: "Support Hub",
        location: "Mandalay",
        salary: 750000,
        up_time: 18,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Annual Bonus * Flexible Working Hours",
        highlight: "Customer Assistance",
        career: "Professional Development",
        l1: "Experience in customer service or related field.",
        l2: "Strong communication skills.",
        l3: "Excellent problem-solving abilities.",
        l4: "Ability to manage multiple tasks and priorities.",
        l5: "Proficiency in customer service software.",
        l6: "Respond to customer inquiries via phone, email, and chat.",
        l7: "Resolve customer issues and ensure satisfaction.",
        l8: "Document customer interactions and feedback."
    },
    {
        job_no: 50,
        job_name: "HR Specialist",
        job_fun: "Customer Service, Support",
        com_name: "Wave Money",
        location: "Yangon",
        salary: 950000,
        up_time: 23,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health Insurance * Retirement Plan * Performance Bonus",
        highlight: "Employee-Focused HR Initiatives",
        career: "HR Certification Programs",
        l1: "Proven experience as an HR specialist or relevant role.",
        l2: "Knowledge of HR processes and best practices.",
        l3: "Strong communication and interpersonal skills.",
        l4: "Ability to handle sensitive information confidentially.",
        l5: "Proficient in HR software and tools.",
        l6: "Assist with recruitment and onboarding processes.",
        l7: "Develop training and development programs.",
        l8: "Ensure compliance with labor regulations."
    },
    {
        job_no: 51,
        job_name: "Language Teacher (Chinese/ Myanmar)",
        job_fun: "Education, Teaching, Childcare",
        com_name: "SHHAM Company Limited",
        location: "Yangon",
        salary: 950000,
        up_time: 23,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "School holidays Competitive salary Performance-based bonus annually",
        highlight: "Friendly & supportive working environment",
        career: "Professional Development Opportunities",
        l1: "Bachelor degree in Education, Language Studies, or a related field. A Master degree is preferred.",
        l2: "Strong proficiency in the target language (Chinese or Myanmar) with excellent communication and interpersonal skills.",
        l3: "Knowledge of language acquisition theories, curriculum frameworks, and assessment practices.",
        l4: "Ability to differentiate instruction and accommodate diverse learning styles, abilities, and cultural backgrounds.",
        l5: "Commitment to ongoing professional growth and development.",
        l6: "Develop and deliver engaging lesson plans that align with the curriculum objectives and cater to the diverse needs of students.",
        l7: "Teach language skills including reading, writing, listening, and speaking, with a focus on grammar, vocabulary, and comprehension.",
        l8: "Employ various teaching methodologies, resources, and technologies to create interactive and dynamic learning experiences."
    },
    {
        job_no: 52,
        job_name: "Marketing/Teaching Assistant",
        job_fun: "Education, Teaching, Childcare",
        com_name: "S.A.M Myanmar",
        location: "Mandalay",
        salary: 950000,
        up_time: 23,
        exp: "Experienced Non-Manager",
        level: "Professional Certificate",
        type: "Full Time",
        benefits: " Rewards for over performance",
        highlight: "Make a difference, Fun working environment, Friendly and warm work place",
        career: "Training provided, Promotion opportunities",
        l1: "Entry level/Undergard students are welcomed.",
        l2: "Proven experience in teaching would be an advantage.",
        l3: "Fluent in English.",
        l4: "A thorough understanding of best practices in teaching.",
        l5: "Basic computing skill.",
        l6: "Distributing learning materials to the students.",
        l7: "Page marketing and messenger reply.",
        l8: "Building a strong relationship with the students."
    },
    {
        job_no: 53,
        job_name: "Primary School Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "PEC School",
        location: "Naypyidaw",
        salary: 900000,
        up_time: 15,
        exp: "Entry Level",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid leave",
        highlight: "Innovative teaching methods",
        career: "Professional development workshops",
        l1: "Bachelor degree in Education or related field.",
        l2: "Experience in primary school teaching preferred.",
        l3: "Strong classroom management skills.",
        l4: "Ability to create engaging lesson plans.",
        l5: "Commitment to fostering a positive learning environment.",
        l6: "Teach core subjects including Math, Science, and English.",
        l7: "Assess student progress and provide feedback.",
        l8: "Utilize technology to enhance learning."
    },
    {
        job_no: 54,
        job_name: "English Language Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "Unity Private School",
        location: "Yangon",
        salary: 1050000,
        up_time: 20,
        exp: "Experienced Non-Manager",
        level: "Master Degree",
        type: "Full Time",
        benefits: "Annual performance bonus, Flexible working hours",
        highlight: "Supportive work environment",
        career: "Opportunities for career advancement",
        l1: "Master degree in English or related field.",
        l2: "Experience teaching English as a second language.",
        l3: "Excellent communication and interpersonal skills.",
        l4: "Knowledge of modern teaching methods and techniques.",
        l5: "Ability to engage students and foster a love of learning.",
        l6: "Plan and deliver effective lessons.",
        l7: "Assess and monitor student progress.",
        l8: "Create a positive learning environment."
    },
    {
        job_no: 55,
        job_name: "Math Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "Min Myanmar",
        location: "Yangon",
        salary: 1000000,
        up_time: 18,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health benefits, Paid time off",
        highlight: "Collaborative work environment",
        career: "Professional development opportunities",
        l1: "Bachelor degree in Mathematics or related field.",
        l2: "Proven experience in teaching mathematics.",
        l3: "Strong problem-solving skills.",
        l4: "Ability to explain complex concepts clearly.",
        l5: "Commitment to continuous learning and professional development.",
        l6: "Develop and deliver math curriculum.",
        l7: "Assess student performance and provide feedback.",
        l8: "Use technology to support learning."
    },
    {
        job_no: 56,
        job_name: "Science Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "NISA",
        location: "Mandalay",
        salary: 950000,
        up_time: 22,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Annual bonus",
        highlight: "Modern teaching facilities",
        career: "Opportunities for career growth",
        l1: "Bachelor degree in Science or related field.",
        l2: "Experience teaching science subjects.",
        l3: "Strong analytical skills.",
        l4: "Ability to create engaging science experiments.",
        l5: "Dedication to student success.",
        l6: "Develop and implement science curriculum.",
        l7: "Evaluate student understanding and progress.",
        l8: "Incorporate technology into lessons."
    },
    {
        job_no: 57,
        job_name: "History Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "THE FIRST",
        location: "Yangon",
        salary: 970000,
        up_time: 19,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health benefits, Paid holidays",
        highlight: "Historical resources and archives",
        career: "Continuing education support",
        l1: "Bachelor degree in History or related field.",
        l2: "Experience in teaching history.",
        l3: "Strong research skills.",
        l4: "Ability to make history engaging and relevant.",
        l5: "Commitment to student development.",
        l6: "Plan and deliver history lessons.",
        l7: "Assess and monitor student progress.",
        l8: "Use primary sources in teaching."
    },
    {
        job_no: 58,
        job_name: "Art Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "Scholastic International School Myanmar",
        location: "Mandalay",
        salary: 900000,
        up_time: 17,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid leave",
        highlight: "Art studio access",
        career: "Professional artist collaborations",
        l1: "Bachelor degree in Fine Arts or related field.",
        l2: "Experience teaching art.",
        l3: "Strong artistic skills.",
        l4: "Ability to inspire creativity in students.",
        l5: "Dedication to fostering artistic growth.",
        l6: "Plan and conduct art classes.",
        l7: "Evaluate student artwork and progress.",
        l8: "Organize art exhibitions."
    },
    {
        job_no: 59,
        job_name: "Physical Education Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "EMPS",
        location: "Yangon",
        salary: 950000,
        up_time: 21,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health benefits, Gym membership",
        highlight: "Modern sports facilities",
        career: "Professional coaching certifications",
        l1: "Bachelor degree in Physical Education or related field.",
        l2: "Experience in teaching physical education.",
        l3: "Strong understanding of physical fitness.",
        l4: "Ability to motivate students.",
        l5: "Commitment to promoting healthy lifestyles.",
        l6: "Develop and implement PE curriculum.",
        l7: "Assess student fitness levels.",
        l8: "Organize sports events."
    },
    {
        job_no: 60,
        job_name: "Music Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "Myanmar International School Yangon",
        location: "Yangon",
        salary: 960000,
        up_time: 16,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid leave",
        highlight: "Music studio access",
        career: "Opportunities for professional performances",
        l1: "Bachelor degree in Music or related field.",
        l2: "Experience in teaching music.",
        l3: "Strong musical skills.",
        l4: "Ability to teach various instruments.",
        l5: "Dedication to student musical development.",
        l6: "Plan and conduct music lessons.",
        l7: "Assess student musical progress.",
        l8: "Organize music performances."
    },
    {
        job_no: 61,
        job_name: "Computer Science Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "S.A.M Myanmar",
        location: "Mandalay",
        salary: 980000,
        up_time: 20,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid leave",
        highlight: "Advanced computer labs",
        career: "Tech industry partnerships",
        l1: "Bachelor degree in Computer Science or related field.",
        l2: "Experience in teaching computer science.",
        l3: "Strong programming skills.",
        l4: "Ability to teach various programming languages.",
        l5: "Commitment to student technological advancement.",
        l6: "Develop and deliver computer science curriculum.",
        l7: "Assess student coding skills.",
        l8: "Incorporate technology in teaching."
    },
    {
        job_no: 62,
        job_name: "Geography Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "S.A.M Myanmar",
        location: "Yangon",
        salary: 950000,
        up_time: 18,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid leave",
        highlight: "Field trip opportunities",
        career: "Professional development in geography",
        l1: "Bachelor degree in Geography or related field.",
        l2: "Experience in teaching geography.",
        l3: "Strong knowledge of geographical concepts.",
        l4: "Ability to make geography interesting.",
        l5: "Commitment to student understanding of the world.",
        l6: "Plan and deliver geography lessons.",
        l7: "Assess student geographical knowledge.",
        l8: "Organize field trips."
    },
    {
        job_no: 63,
        job_name: "French Language Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "SHHAM Company Limited",
        location: "Yangon",
        salary: 1000000,
        up_time: 19,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Annual bonus",
        highlight: "Language immersion programs",
        career: "Opportunities for cultural exchange",
        l1: "Bachelor degree in French or related field.",
        l2: "Experience in teaching French.",
        l3: "Strong command of the French language.",
        l4: "Ability to create engaging language lessons.",
        l5: "Dedication to student language acquisition.",
        l6: "Plan and conduct French classes.",
        l7: "Assess student language skills.",
        l8: "Organize cultural activities."
    },
    {
        job_no: 64,
        job_name: "Biology Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "Unity Private School",
        location: "Yangon",
        salary: 1050000,
        up_time: 17,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid leave",
        highlight: "State-of-the-art lab facilities",
        career: "Research opportunities",
        l1: "Bachelor degree in Biology or related field.",
        l2: "Experience in teaching biology.",
        l3: "Strong understanding of biological concepts.",
        l4: "Ability to conduct lab experiments.",
        l5: "Commitment to scientific education.",
        l6: "Develop and deliver biology curriculum.",
        l7: "Assess student understanding of biology.",
        l8: "Supervise lab work."
    },
    {
        job_no: 65,
        job_name: "Chemistry Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "Unity Private School",
        location: "Mandalay",
        salary: 950000,
        up_time: 21,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid holidays",
        highlight: "Modern chemistry labs",
        career: "Continuing education support",
        l1: "Bachelor degree in Chemistry or related field.",
        l2: "Experience in teaching chemistry.",
        l3: "Strong analytical skills.",
        l4: "Ability to conduct chemical experiments.",
        l5: "Dedication to student scientific understanding.",
        l6: "Plan and deliver chemistry lessons.",
        l7: "Assess student knowledge of chemistry.",
        l8: "Supervise lab activities."
    },
    {
        job_no: 66,
        job_name: "Physics Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "THE FIRST",
        location: "Yangon",
        salary: 1000000,
        up_time: 16,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid leave",
        highlight: "Advanced physics lab",
        career: "Opportunities for scientific research",
        l1: "Bachelor degree in Physics or related field.",
        l2: "Experience in teaching physics.",
        l3: "Strong understanding of physical principles.",
        l4: "Ability to conduct physics experiments.",
        l5: "Commitment to fostering scientific curiosity.",
        l6: "Develop and deliver physics curriculum.",
        l7: "Assess student understanding of physics.",
        l8: "Supervise lab experiments."
    },
    {
        job_no: 67,
        job_name: "Social Studies Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "PEC School",
        location: "Mandalay",
        salary: 950000,
        up_time: 18,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid holidays",
        highlight: "Collaborative learning environment",
        career: "Professional development workshops",
        l1: "Bachelor degree in Social Studies or related field.",
        l2: "Experience in teaching social studies.",
        l3: "Strong understanding of social sciences.",
        l4: "Ability to make social studies engaging.",
        l5: "Dedication to student understanding of society.",
        l6: "Plan and deliver social studies lessons.",
        l7: "Assess student knowledge of social studies.",
        l8: "Organize community activities."
    },
    {
        job_no: 68,
        job_name: "Economics Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "Myanmar Polyland Academy",
        location: "Yangon",
        salary: 980000,
        up_time: 17,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Annual bonus",
        highlight: "Real-world economics projects",
        career: "Professional networking opportunities",
        l1: "Bachelor degree in Economics or related field.",
        l2: "Experience in teaching economics.",
        l3: "Strong analytical skills.",
        l4: "Ability to explain economic concepts clearly.",
        l5: "Commitment to student economic understanding.",
        l6: "Plan and deliver economics curriculum.",
        l7: "Assess student understanding of economics.",
        l8: "Organize economic discussions."
    },
    {
        job_no: 69,
        job_name: "Business Studies Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "Myanmar International School Yangon",
        location: "Mandalay",
        salary: 950000,
        up_time: 20,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid leave",
        highlight: "Business simulation games",
        career: "Industry connections and internships",
        l1: "Bachelor degree in Business or related field.",
        l2: "Experience in teaching business studies.",
        l3: "Strong understanding of business concepts.",
        l4: "Ability to make business studies relevant.",
        l5: "Commitment to student entrepreneurial skills.",
        l6: "Develop and deliver business studies curriculum.",
        l7: "Assess student knowledge of business.",
        l8: "Organize business competitions."
    },
    {
        job_no: 70,
        job_name: "Computer Science Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "Myanmar International School Yangon",
        location: "Yangon",
        salary: 1020000,
        up_time: 19,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid holidays",
        highlight: "Access to cutting-edge technology",
        career: "Partnerships with tech companies",
        l1: "Bachelor degree in Computer Science or related field.",
        l2: "Experience in teaching computer science.",
        l3: "Strong programming skills.",
        l4: "Ability to teach various programming languages.",
        l5: "Commitment to student technological advancement.",
        l6: "Develop and deliver computer science curriculum.",
        l7: "Assess student coding skills.",
        l8: "Incorporate technology in teaching."
    },
    {
        job_no: 71,
        job_name: "Computer Science Teacher",
        job_fun: "Education, Teaching, Childcare",
        com_name: "Scholastic International School Myanmar",
        location: "Yangon",
        salary: 1020000,
        up_time: 19,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid holidays",
        highlight: "Access to cutting-edge technology",
        career: "Partnerships with tech companies",
        l1: "Bachelor degree in Computer Science or related field.",
        l2: "Experience in teaching computer science.",
        l3: "Strong programming skills.",
        l4: "Ability to teach various programming languages.",
        l5: "Commitment to student technological advancement.",
        l6: "Develop and deliver computer science curriculum.",
        l7: "Assess student coding skills.",
        l8: "Incorporate technology in teaching."
    },
    {
        job_no: 72,
        job_name: "Language Teacher (Chinese/ Myanmar)",
        job_fun: "Education, Teaching, Childcare",
        com_name: "Min Dhama Co.,Ltd",
        location: "Yangon",
        salary: 1020000,
        up_time: 19,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Health insurance, Paid holidays",
        highlight: "Access to cutting-edge technology",
        career: "Partnerships with tech companies",
        l1: "Bachelor degree (Any Major) or engineering background is preferred.",
        l2: "Chinese Language (Native speaker or 4 skills)",
        l3: "Microsoft office ( word, excel, PowerPoint )",
        l4: "1 or 2-years experiences in related field.",
        l5: "Ability to differentiate instruction and accommodate diverse learning styles, abilities, and cultural backgrounds.",
        l6: "Responsible for necessary arrangement, implementation, inspection, supervision of specific management work for operation as per factory manager instruction.",
        l7: "Collaborate with other departments to provide language support and ensure translations meet company standards and requirements.",
        l8: "Responsible for the classification and submission of various documentation process."
    },
    {
        job_no: 73,
        job_name: "Thai Translator",
        job_fun: "Translation",
        com_name: "MKOL Co.,Ltd",
        location: "Yangon",
        salary: 1020000,
        up_time: 19,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "OT, Monthly Allowance",
        highlight: "fun working environment",
        career: "training Provided, New Opportunity",
        l1: "Education: Any graduate Degree holder or Other Educationanl Level",
        l2: "Experience; prefer 2 or 3 years in related field.",
        l3: "Must know 4 skills in Thai and can use email.",
        l4: "Must knowledge of computing (Microsoft word, excel etc.,)",
        l5: "Good in Thai to Myanmar Translation & Sepaking , Written",
        l6: "Education: Any graduate Degree holder or Other Educationanl Level",
        l7: "Experience; prefer 2 or 3 years in related field.",
        l8: "Must know 4 skills in Thai and can use email."
    },
    {
        job_no: 74,
        job_name: "Japanese Interpreter",
        job_fun: "Translation",
        com_name: "Pan Tha Pyay Company Limited",
        location: "Yangon",
        salary: 1020000,
        up_time: 19,
        exp: "Experienced Non-Manager",
        level: "Bachelor Degree",
        type: "Full Time",
        benefits: "Bonus, Overtime payments",
        highlight: "Join An Experienced Team",
        career: "Learn New Skills on the job",
        l1: "JLPT or Nat-test or J-test N3 Passed",
        l2: "Can speak  & write & read",
        l3: "communicate with Japanese people and also Myanmar translation ",
        l4: "communicate through interviews & meetings",
        l5: "advanced computer level",
        l6: "Must know 4 skills in Japanese and can use email.",
        l7: "Assist in translating written documents, such as emails, reports, and presentations, from Japanese to Myanmar.",
        l8: "Provide accurate interpretation between Japanese and Myanmar languages during meetings, interview, and other business-related events."
    },
    
];


